services:
  # Web service
  - type: web
    name: fullstack-electronics
    runtime: docker
    region: oregon
    plan: standard
    healthCheckPath: /djangoapp/health-check
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: electronicsretail-e-commerce.onrender.com,localhost,127.0.0.1
      - key: EXPRESS_API_URL
        value: http://127.0.0.1:3030
      - key: SENTIMENT_ANALYZER_URL
        value: http://127.0.0.1:5002/
      - key: MONGODB_URI
        sync: false  # User must provide this manually in the dashboard
