services:
  # Web service
  - type: web
    name: fullstack-electronics
    runtime: docker
    region: oregon
    plan: standard
    healthCheckPath: /health/
    
    # Using Secret Files instead of environment variables
    # All sensitive configuration will be loaded from these files
    secretFiles:
      - key: SECRETS_ENV
        fromFile: secrets.env
        mountPath: /etc/secrets/secrets.env
      - key: WATSONX_CONFIG
        fromFile: watsonx.json
        mountPath: /etc/secrets/watsonx.json
    
    # Minimal environment variables - most config comes from secret files
    envVars:
      # Set PORT for Render
      - key: PORT
        value: "8000"
