# Generated by Django 5.2.3 on 2025-07-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_order_notes_order_processed_at_order_processed_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
    ]
